//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingPlanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class AerobneVjezbeSlike
    {
        public int AerobnaVjezbaSlikaId { get; set; }
        public int AerobneVjezbePopisAerobnaVjezbaId { get; set; }
        public string AerobnaVjezbaSlikaIme { get; set; }
    
        public virtual AerobneVjezbePopis AerobneVjezbePopis { get; set; }
    }
}
