//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingPlanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class AerobneVjezbePopis
    {
        public AerobneVjezbePopis()
        {
            this.AerobneVjezbeSlike = new HashSet<AerobneVjezbeSlike>();
            this.AerobneVjezbe = new HashSet<AerobneVjezbe>();
        }
    
        public int AerobnaVjezbaId { get; set; }
        public string Naziv { get; set; }
        public string Info { get; set; }
    
        public virtual ICollection<AerobneVjezbeSlike> AerobneVjezbeSlike { get; set; }
        public virtual ICollection<AerobneVjezbe> AerobneVjezbe { get; set; }
    }
}
