//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingPlanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnaerobneVjezbe
    {
        public int AnaerobnaVjezbaId { get; set; }
        public string Naziv { get; set; }
        public string Puls { get; set; }
        public string Tempo { get; set; }
        public string BrojSprintova { get; set; }
        public string Odmor { get; set; }
        public string Napomena { get; set; }
        public int AnaerobneVjezbePopisAnaerobnaVjezbaId { get; set; }
        public int SekcijaVjezbiSekcijaId { get; set; }
        public string Info { get; set; }
        public string TrajanjeSprinta { get; set; }
    
        public virtual AnaerobneVjezbePopis AnaerobneVjezbePopis { get; set; }
        public virtual SekcijaVjezbi SekcijaVjezbi { get; set; }
    }
}
