//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingPlanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnaerobneVjezbeSlike
    {
        public int AnaerobnaVjezbaSlikaId { get; set; }
        public int AnaerobneVjezbePopisAnaerobnaVjezbaId { get; set; }
        public string AnaerobnaVjezbaSlikaIme { get; set; }
    
        public virtual AnaerobneVjezbePopis AnaerobneVjezbePopis { get; set; }
    }
}
