//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingPlanner
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using TrainingPlanner.Models;

    [MetadataType(typeof(AntropometrijaMetadata))]
    public partial class Antropometrija
    {
        public int AntropometrijaId { get; set; }
        public string Ime { get; set; }
        public string Visina { get; set; }
        public string Tezina { get; set; }
        public string PotkoznoMasnoTkivo { get; set; }
        public string BezmasnaMasa { get; set; }
        public int ClanClanId { get; set; }
    
        public virtual Clan Clan { get; set; }
    }
}
