//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingPlanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Istezanje
    {
        public int IstezanjeId { get; set; }
        public string Naziv { get; set; }
        public string Info { get; set; }
        public int TreningId { get; set; }
        public string VrijemeIzdrzaja { get; set; }
        public string VrstaIstezanja { get; set; }
        public int IstezanjePopisIstezanjeId { get; set; }
        public int IstezanjeTreningTemplateIstezanjeTreningTemplateId { get; set; }
    
        public virtual Trening Trening { get; set; }
        public virtual IstezanjePopis IstezanjePopis { get; set; }
        public virtual IstezanjeTreningTemplate IstezanjeTreningTemplate { get; set; }
    }
}
