//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingPlanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class IstezanjeSlike
    {
        public int IstezanjeSlikeId { get; set; }
        public string IstezanjeSlikaIme { get; set; }
        public int IstezanjePopisIstezanjeId { get; set; }
    
        public virtual IstezanjePopis IstezanjePopis { get; set; }
    }
}
