//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingPlanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class IstezanjeT
    {
        public int IstezanjeTId { get; set; }
        public string NazivT { get; set; }
        public string InfoT { get; set; }
        public int IstezanjePopisIstezanjeId { get; set; }
        public int IstezanjeTreningTemplateIstezanjeTreningTemplateId { get; set; }
    
        public virtual IstezanjePopis IstezanjePopis { get; set; }
        public virtual IstezanjeTreningTemplate IstezanjeTreningTemplate { get; set; }
    }
}
