//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingPlanner
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using TrainingPlanner.Models;

    [MetadataType(typeof(IstezanjePopisMetadata))]
    public partial class IstezanjePopis
    {
        public IstezanjePopis()
        {
            this.IstezanjeSlike = new HashSet<IstezanjeSlike>();
        }
    
        public int IstezanjeId { get; set; }
        public string Naziv { get; set; }
        public string Info { get; set; }
    
        public virtual ICollection<IstezanjeSlike> IstezanjeSlike { get; set; }
    }
}
