//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingPlanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class IstezanjePopis
    {
        public IstezanjePopis()
        {
            this.IstezanjeSlike = new HashSet<IstezanjeSlike>();
            this.Istezanje = new HashSet<Istezanje>();
        }
    
        public int IstezanjeId { get; set; }
        public string Naziv { get; set; }
        public string Info { get; set; }
    
        public virtual ICollection<IstezanjeSlike> IstezanjeSlike { get; set; }
        public virtual ICollection<Istezanje> Istezanje { get; set; }
    }
}
