//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingPlanner
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using TrainingPlanner.Models;

    [MetadataType(typeof(RezultatiTestMetadata))]
    public partial class RezultatiTest
    {
        public int ReszultatiTestId { get; set; }
        public int TestId { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public string Rezultat { get; set; }
    
        public virtual Test Test { get; set; }
    }
}
