//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingPlanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class SekcijaVjezbi
    {
        public SekcijaVjezbi()
        {
            this.Vjezba = new HashSet<Vjezba>();
            this.AerobneVjezbe = new HashSet<AerobneVjezbe>();
            this.AnaerobneVjezbe = new HashSet<AnaerobneVjezbe>();
        }
    
        public int SekcijaId { get; set; }
        public int TreningId { get; set; }
        public string BrojKrugova { get; set; }
        public string Odmor { get; set; }
    
        public virtual Trening Trening { get; set; }
        public virtual ICollection<Vjezba> Vjezba { get; set; }
        public virtual ICollection<AerobneVjezbe> AerobneVjezbe { get; set; }
        public virtual ICollection<AnaerobneVjezbe> AnaerobneVjezbe { get; set; }
    }
}
