//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingPlanner
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using TrainingPlanner.Models;

    [MetadataType(typeof(TestMetadata))]
    public partial class Test
    {
        public Test()
        {
            this.Slika = new HashSet<Slika>();
            this.RezultatiTest = new HashSet<RezultatiTest>();
        }
    
        public int TestId { get; set; }
        public System.DateTime DatumTesta { get; set; }
        public string Name { get; set; }
        public int ClanId { get; set; }
        public string FunkcionalneSposobnosti { get; set; }
        public string MotorickeSposobnosti { get; set; }
        public string NapomenaFunkcionalneSposobnosti { get; set; }
        public string NapomenaMotorickeSposobnosti { get; set; }
    
        public virtual Clan Clan { get; set; }
        public virtual ICollection<Slika> Slika { get; set; }
        public virtual ICollection<RezultatiTest> RezultatiTest { get; set; }
    }
}
