//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingPlanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trening
    {
        public Trening()
        {
            this.Zagrijavanje = new HashSet<Zagrijavanje>();
            this.Istezanje = new HashSet<Istezanje>();
            this.SekcijaVjezbi = new HashSet<SekcijaVjezbi>();
        }
    
        public int TreningId { get; set; }
        public string TipTreninga { get; set; }
        public Nullable<System.DateTime> DatumTreninga { get; set; }
        public string ImeTreninga { get; set; }
        public int ClanId { get; set; }
        public string Napomena { get; set; }
    
        public virtual Clan Clan { get; set; }
        public virtual ICollection<Zagrijavanje> Zagrijavanje { get; set; }
        public virtual ICollection<Istezanje> Istezanje { get; set; }
        public virtual ICollection<SekcijaVjezbi> SekcijaVjezbi { get; set; }
    }
}
