//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingPlanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class VjezbePopis
    {
        public VjezbePopis()
        {
            this.VjezbeSlike = new HashSet<VjezbeSlike>();
            this.Vjezba = new HashSet<Vjezba>();
        }
    
        public int VjezbeId { get; set; }
        public string ImeVjezbe { get; set; }
        public byte[] Slika { get; set; }
        public string Info { get; set; }
    
        public virtual ICollection<VjezbeSlike> VjezbeSlike { get; set; }
        public virtual ICollection<Vjezba> Vjezba { get; set; }
    }
}
