//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingPlanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZagrijavanjeSkupina
    {
        public ZagrijavanjeSkupina()
        {
            this.Zagrijavanje = new HashSet<Zagrijavanje>();
            this.VjezbaZagrijavanje = new HashSet<VjezbaZagrijavanje>();
        }
    
        public int ZagrijavanjeSkupinaId { get; set; }
        public string PopisZagrijavanja { get; set; }
        public int TreningTreningId { get; set; }
    
        public virtual ICollection<Zagrijavanje> Zagrijavanje { get; set; }
        public virtual Trening Trening { get; set; }
        public virtual ICollection<VjezbaZagrijavanje> VjezbaZagrijavanje { get; set; }
    }
}
