//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingPlanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZagrijavanjeSlike
    {
        public int ZagrijavanjeSlikeId { get; set; }
        public int ZagrijavanjePopisZagrijavanjeId { get; set; }
        public string ZagrijavanjeSlikaIme { get; set; }
    
        public virtual ZagrijavanjePopis ZagrijavanjePopis { get; set; }
    }
}
