//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using TrainingPlanner.Models;

namespace TrainingPlanner
{
    using System;
    using System.Collections.Generic;

    [MetadataType(typeof(ZagrijavanjePopisMetadata))]
    public partial class ZagrijavanjePopis
    {
        public ZagrijavanjePopis()
        {
            this.ZagrijavanjeSlike = new HashSet<ZagrijavanjeSlike>();
            this.Zagrijavanje = new HashSet<Zagrijavanje>();
        }
    
        public int ZagrijavanjeId { get; set; }
        public string Naziv { get; set; }
        public string Info { get; set; }
    
        public virtual ICollection<ZagrijavanjeSlike> ZagrijavanjeSlike { get; set; }
        public virtual ICollection<Zagrijavanje> Zagrijavanje { get; set; }
    }
}
